plugins {
	id 'org.springframework.boot' version '4.0.5'
}

ext {
	set('springCloudVersion', "2025.1.1")
	set('springGrpcVersion', "1.0.2")
}

dependencies {
	implementation project(':libs:common-web')
	implementation project(':libs:common-jpa')
	implementation project(':libs:common-observability')
	implementation project(':libs:proto')
	implementation 'org.springframework.boot:spring-boot-starter-kafka'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'net.javacrumbs.shedlock:shedlock-spring:6.9.1'
	implementation 'net.javacrumbs.shedlock:shedlock-provider-redis-spring:6.9.1'
	implementation 'io.grpc:grpc-services'
	implementation 'org.springframework.grpc:spring-grpc-server-spring-boot-starter'
	implementation 'org.springframework.grpc:spring-grpc-client-spring-boot-starter'
	implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
	annotationProcessor 'com.querydsl:querydsl-apt:5.1.0:jakarta'
	annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
	annotationProcessor 'jakarta.persistence:jakarta.persistence-api'
	runtimeOnly 'org.postgresql:postgresql'
	testRuntimeOnly 'com.h2database:h2'
	testImplementation 'org.springframework.boot:spring-boot-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-kafka-test'
	testImplementation 'org.springframework.grpc:spring-grpc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
		mavenBom "org.springframework.grpc:spring-grpc-dependencies:${springGrpcVersion}"
	}
}
