spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/routine_db
    password: ${DB_PASSWORD:localpassword}
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

gateway:
  secret: ${GATEWAY_SECRET:local-secret}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
